services:
  database:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kontabb-development
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
