CREATE TABLE "documentos_fiscais_itens" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"documento_fiscal_id" uuid NOT NULL,
	"cliente_id" uuid NOT NULL,
	"numero_item" integer NOT NULL,
	"codigo_produto" text NOT NULL,
	"codigo_ean" text,
	"descricao" text NOT NULL,
	"ncm" varchar(8),
	"nve" text,
	"cest" varchar(7),
	"ind_escala" varchar(1),
	"cnpj_fabricante" varchar(14),
	"codigo_beneficio_fiscal" text,
	"cfop" varchar(4) NOT NULL,
	"unidade_comercial" varchar(10) NOT NULL,
	"quantidade_comercial" numeric(15, 4) NOT NULL,
	"valor_unitario_comercial" numeric(21, 10) NOT NULL,
	"valor_bruto_produto" numeric(15, 2) NOT NULL,
	"codigo_ean_tributavel" text,
	"unidade_tributavel" varchar(10),
	"quantidade_tributavel" numeric(15, 4),
	"valor_unitario_tributavel" numeric(21, 10),
	"valor_frete" numeric(15, 2),
	"valor_seguro" numeric(15, 2),
	"valor_desconto" numeric(15, 2),
	"valor_outras_despesas" numeric(15, 2),
	"ind_total" varchar(1) NOT NULL,
	"numero_pedido_compra" text,
	"item_pedido_compra" text,
	"informacoes_adicionais" text,
	"origem_mercadoria" varchar(1),
	"cst_icms" varchar(3),
	"csosn_icms" varchar(4),
	"modalidade_bc_icms" varchar(1),
	"percentual_reducao_bc_icms" numeric(7, 4),
	"valor_bc_icms" numeric(15, 2),
	"aliquota_icms" numeric(7, 4),
	"valor_icms" numeric(15, 2),
	"modalidade_bc_icms_st" varchar(1),
	"percentual_mva_st" numeric(7, 4),
	"percentual_reducao_bc_icms_st" numeric(7, 4),
	"valor_bc_icms_st" numeric(15, 2),
	"aliquota_icms_st" numeric(7, 4),
	"valor_icms_st" numeric(15, 2),
	"valor_bc_fcp" numeric(15, 2),
	"aliquota_fcp" numeric(7, 4),
	"valor_fcp" numeric(15, 2),
	"valor_bc_fcp_st" numeric(15, 2),
	"aliquota_fcp_st" numeric(7, 4),
	"valor_fcp_st" numeric(15, 2),
	"motivo_desoneracao_icms" varchar(2),
	"valor_icms_desonerado" numeric(15, 2),
	"percentual_diferimento" numeric(7, 4),
	"valor_icms_diferido" numeric(15, 2),
	"valor_icms_operacao" numeric(15, 2),
	"aliquota_credito_sn" numeric(7, 4),
	"valor_credito_icms_sn" numeric(15, 2),
	"valor_bc_icms_st_retido" numeric(15, 2),
	"aliquota_icms_st_retido" numeric(7, 4),
	"valor_icms_st_retido" numeric(15, 2),
	"valor_bc_icms_uf_dest" numeric(15, 2),
	"valor_bc_fcp_uf_dest" numeric(15, 2),
	"percentual_fcp_uf_dest" numeric(7, 4),
	"aliquota_icms_uf_dest" numeric(7, 4),
	"aliquota_icms_interestadual" numeric(7, 4),
	"percentual_provisorio_partilha" numeric(7, 4),
	"valor_fcp_uf_dest" numeric(15, 2),
	"valor_icms_uf_dest" numeric(15, 2),
	"valor_icms_uf_remetente" numeric(15, 2),
	"cst_ipi" varchar(2),
	"classe_enquadramento_ipi" varchar(5),
	"codigo_enquadramento_ipi" varchar(3),
	"cnpj_produtor_ipi" varchar(14),
	"valor_bc_ipi" numeric(15, 2),
	"aliquota_ipi" numeric(7, 4),
	"quantidade_unidade_ipi" numeric(15, 4),
	"valor_unidade_ipi" numeric(15, 4),
	"valor_ipi" numeric(15, 2),
	"cst_pis" varchar(2),
	"valor_bc_pis" numeric(15, 2),
	"aliquota_pis_percentual" numeric(7, 4),
	"quantidade_bc_pis" numeric(15, 4),
	"aliquota_pis_reais" numeric(15, 4),
	"valor_pis" numeric(15, 2),
	"valor_bc_pis_st" numeric(15, 2),
	"aliquota_pis_st_percentual" numeric(7, 4),
	"valor_pis_st" numeric(15, 2),
	"cst_cofins" varchar(2),
	"valor_bc_cofins" numeric(15, 2),
	"aliquota_cofins_percentual" numeric(7, 4),
	"quantidade_bc_cofins" numeric(15, 4),
	"aliquota_cofins_reais" numeric(15, 4),
	"valor_cofins" numeric(15, 2),
	"valor_bc_cofins_st" numeric(15, 2),
	"aliquota_cofins_st_percentual" numeric(7, 4),
	"valor_cofins_st" numeric(15, 2),
	"valor_bc_ii" numeric(15, 2),
	"valor_despesa_aduaneira" numeric(15, 2),
	"valor_imposto_importacao" numeric(15, 2),
	"valor_iof" numeric(15, 2),
	"valor_tributos_aproximados" numeric(15, 2),
	"criado_em" timestamp DEFAULT now() NOT NULL,
	"atualizado_em" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "chk_item_numero" CHECK ("documentos_fiscais_itens"."numero_item" BETWEEN 1 AND 990),
	CONSTRAINT "chk_item_ind_escala" CHECK ("documentos_fiscais_itens"."ind_escala" IS NULL OR "documentos_fiscais_itens"."ind_escala" IN ('S', 'N')),
	CONSTRAINT "chk_item_ind_total" CHECK ("documentos_fiscais_itens"."ind_total" IN ('0', '1')),
	CONSTRAINT "chk_item_origem" CHECK ("documentos_fiscais_itens"."origem_mercadoria" IS NULL OR "documentos_fiscais_itens"."origem_mercadoria" ~ '^[0-8]$'),
	CONSTRAINT "chk_item_cfop" CHECK ("documentos_fiscais_itens"."cfop" ~ '^[1-7][0-9]{3}$')
);
--> statement-breakpoint
ALTER TABLE "documentos_fiscais_itens" ADD CONSTRAINT "documentos_fiscais_itens_documento_fiscal_id_documentos_fiscais_id_fk" FOREIGN KEY ("documento_fiscal_id") REFERENCES "public"."documentos_fiscais"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "documentos_fiscais_itens" ADD CONSTRAINT "documentos_fiscais_itens_cliente_id_clientes_id_fk" FOREIGN KEY ("cliente_id") REFERENCES "public"."clientes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uidx_item_doc_num" ON "documentos_fiscais_itens" USING btree ("documento_fiscal_id","numero_item");--> statement-breakpoint
CREATE INDEX "idx_item_cliente_id" ON "documentos_fiscais_itens" USING btree ("cliente_id");--> statement-breakpoint
CREATE INDEX "idx_item_cfop" ON "documentos_fiscais_itens" USING btree ("cfop");--> statement-breakpoint
CREATE INDEX "idx_item_cst_icms" ON "documentos_fiscais_itens" USING btree ("cst_icms");--> statement-breakpoint
CREATE INDEX "idx_item_csosn_icms" ON "documentos_fiscais_itens" USING btree ("csosn_icms");--> statement-breakpoint
CREATE INDEX "idx_item_cst_pis" ON "documentos_fiscais_itens" USING btree ("cst_pis");--> statement-breakpoint
CREATE INDEX "idx_item_cst_cofins" ON "documentos_fiscais_itens" USING btree ("cst_cofins");--> statement-breakpoint
CREATE INDEX "idx_item_ncm" ON "documentos_fiscais_itens" USING btree ("ncm");