/**
 * PDF text extraction and parsing for payroll (folha de pagamento) documents.
 * Handles PDFs generated by payroll systems like Senior, Dominio, Alterdata.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Interfaces
// ─────────────────────────────────────────────────────────────────────────────

export interface RubricaFolha {
  codigo: string;
  descricao: string;
  tipo: 'PROVENTO' | 'DESCONTO';
  valor: number;
}

export interface DadosFuncionarioFolha {
  codigoFuncionario: string;
  nomeCompleto: string;
  referencia: string | null;
  codigoFolha: string | null;
  dataAdmissao: string | null;
  dependentesIr: number;
  dependentesSf: number;
  cargo: string | null;
  salarioBase: number;
  totalProventos: number;
  totalDescontos: number;
  salarioLiquido: number;
  baseInss: number | null;
  aliquotaInss: number | null;
  valorInss: number | null;
  baseFgts: number | null;
  valorFgts: number | null;
  baseIrrf: number | null;
  valorIrrf: number | null;
  rubricas: RubricaFolha[];
}

export interface DadosFolhaPagamento {
  cnpj: string;
  razaoSocial: string;
  competencia: string;
  periodoInicio: string;
  periodoFim: string;
  funcionarios: DadosFuncionarioFolha[];
  totalBruto: number;
  totalDescontos: number;
  totalLiquido: number;
  totalFuncionarios: number;
  totalInss: number;
  totalFgts: number;
  totalIrrf: number;
  totalSalarioFamilia: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function parseBRL(str: string): number {
  if (!str) return 0;
  return parseFloat(str.replace(/\./g, '').replace(',', '.'));
}

function formatCnpj(digits: string): string {
  const d = digits.replace(/\D/g, '');
  if (d.length !== 14) return digits;
  return d.replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, '$1.$2.$3/$4-$5');
}

function classificarRubrica(codigo: string): 'PROVENTO' | 'DESCONTO' {
  const num = parseInt(codigo, 10);
  // Common discount ranges in Brazilian payroll systems:
  // 600-699: Loan deductions, transportation vouchers, etc.
  // 900-999: INSS, IRRF, union fees, etc.
  if (num >= 900 || (num >= 600 && num < 700)) return 'DESCONTO';
  return 'PROVENTO';
}

// ─────────────────────────────────────────────────────────────────────────────
// Main extraction function
// ─────────────────────────────────────────────────────────────────────────────

export function extractDadosFolhaPagamento(
  text: string,
): DadosFolhaPagamento | null {
  // Step 1: Validate it's a payroll document
  if (!text.includes('FOLHA DE PAGAMENTO')) {
    return null;
  }

  // Step 2: Extract CNPJ
  // In the extracted text the CNPJ digits appear BEFORE "CNPJ/CEI:" (e.g. "03198283000116CNPJ/CEI:")
  const cnpjMatch =
    text.match(/(\d{14})CNPJ\/CEI:/) ||
    text.match(/CNPJ\/CEI:\s*(\d{14}|\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2})/);
  if (!cnpjMatch) return null;
  const cnpjRaw = cnpjMatch[1].replace(/\D/g, '');
  const cnpj = formatCnpj(cnpjRaw);

  // Step 3: Extract razao social (between company code and "Empresa :")
  let razaoSocial = '';
  const razaoMatch = text.match(/^\d{5}(.+?)Empresa\s*:/);
  if (razaoMatch) {
    razaoSocial = razaoMatch[1].trim();
  }

  // Step 4: Extract period
  const periodoMatch = text.match(
    /Ref\.:\s*\([^)]*\)\s*(\d{2})\/(\d{2})\/(\d{4})\s+(\d{2})\/(\d{2})\/(\d{4})/,
  );
  if (!periodoMatch) return null;

  const [, diaInicio, mesInicio, anoInicio, diaFim, mesFim, anoFim] =
    periodoMatch;
  const periodoInicio = `${anoInicio}-${mesInicio}-${diaInicio}`;
  const periodoFim = `${anoFim}-${mesFim}-${diaFim}`;
  const competencia = `${mesInicio}/${anoInicio}`;

  // Step 5: Remove repeated page headers from multi-page PDFs
  // Page headers look like: "00013MERCADINHO...Empresa : End. : Ref.: (...) DD/MM/YYYY DD/MM/YYYYa Dpto : Página : NNNNN Código Nome Ref. Sal. Contratual Adicionais Descontos Líquido TODOS Recibo FOLHA DE PAGAMENTO XXXXXXXXXXXXXX CNPJ/CEI:"
  // Keep only the first occurrence, remove subsequent ones.
  const pageHeaderPattern =
    /\d{5}[A-ZÁÉÍÓÚÃÕÂÊÎÔÛÇÀÈÌÒÙa-záéíóúãõâêîôûçàèìòù\s.,]+?Empresa\s*:.*?FOLHA DE PAGAMENTO\s+\d{14}CNPJ\/CEI:\s*/g;
  let cleanedText = text;
  const headerMatches = [...text.matchAll(pageHeaderPattern)];
  if (headerMatches.length > 1) {
    // Remove all headers except the first one
    for (let i = headerMatches.length - 1; i >= 1; i--) {
      const hMatch = headerMatches[i];
      cleanedText =
        cleanedText.substring(0, hMatch.index!) +
        cleanedText.substring(hMatch.index! + hMatch[0].length);
    }
  }

  // Step 6: Split into employee blocks
  const cnpjPos = cleanedText.indexOf(cnpjMatch[0]);
  const textAfterCnpj = cleanedText.substring(cnpjPos + cnpjMatch[0].length);

  // Find the summary section
  const resumoIdx = textAfterCnpj.indexOf('Resumo da folha');
  const employeeSection =
    resumoIdx !== -1 ? textAfterCnpj.substring(0, resumoIdx) : textAfterCnpj;

  // Find start positions of each employee (6-digit code followed by uppercase name)
  const employeeStarts: number[] = [];
  const codePattern = /\b(\d{6})\s+([A-ZÁÉÍÓÚÃÕÂÊÎÔÛÇÀÈÌÒÙ]{2,})/g;
  let codeMatch: RegExpExecArray | null;
  while ((codeMatch = codePattern.exec(employeeSection)) !== null) {
    employeeStarts.push(codeMatch.index);
  }

  const funcionarios: DadosFuncionarioFolha[] = [];

  for (let i = 0; i < employeeStarts.length; i++) {
    const start = employeeStarts[i];
    const end =
      i + 1 < employeeStarts.length
        ? employeeStarts[i + 1]
        : employeeSection.length;
    const block = employeeSection.substring(start, end);
    const funcionario = parseEmployeeBlock(block);
    if (funcionario) {
      funcionarios.push(funcionario);
    }
  }

  // Step 7: Extract footer totals (use original text for resumo since it might span pages)
  const resumoIdxFull = text.indexOf('Resumo da folha');
  const resumoText = resumoIdxFull !== -1 ? text.substring(resumoIdxFull) : '';
  const totals = extractTotals(resumoText, text);

  return {
    cnpj,
    razaoSocial,
    competencia,
    periodoInicio,
    periodoFim,
    funcionarios,
    totalBruto: totals.totalBruto,
    totalDescontos: totals.totalDescontos,
    totalLiquido: totals.totalLiquido,
    totalFuncionarios: totals.totalFuncionarios || funcionarios.length,
    totalInss: totals.totalInss,
    totalFgts: totals.totalFgts,
    totalIrrf: totals.totalIrrf,
    totalSalarioFamilia: totals.totalSalarioFamilia,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Employee block parser
// ─────────────────────────────────────────────────────────────────────────────

function parseEmployeeBlock(block: string): DadosFuncionarioFolha | null {
  // Extract employee code (6 digits) and name
  const codeNameMatch = block.match(
    /(\d{6})\s+([A-ZÁÉÍÓÚÃÕÂÊÎÔÛÇÀÈÌÒÙ][A-ZÁÉÍÓÚÃÕÂÊÎÔÛÇÀÈÌÒÙ\s]+?)\s+\d/,
  );
  if (!codeNameMatch) return null;

  const codigoFuncionario = codeNameMatch[1];
  const nomeCompleto = codeNameMatch[2].trim();

  // Extract admissão date
  const admissaoMatch = block.match(/(\d{2}\/\d{2}\/\d{4})Admiss[aã]o/);
  const dataAdmissao = admissaoMatch ? admissaoMatch[1] : null;

  // Extract dependentes IR and SF
  const depIrMatch = block.match(/Dep\s*IR\s*:\s*(\d+)/);
  const depSfMatch = block.match(/Dep\s*SF\s*:\s*(\d+)/);
  const dependentesIr = depIrMatch ? parseInt(depIrMatch[1], 10) : 0;
  const dependentesSf = depSfMatch ? parseInt(depSfMatch[1], 10) : 0;

  // Extract cargo/função
  // Cargo can contain parentheses like REPOSITOR(A), INST.DE MUSCULAÇÃO, etc.
  // After the cargo there may be vacation info ("Férias de ...") or "Salário Base"
  const cargoMatch = block.match(
    /Fun[cç][aã]o\s*:\s*([A-ZÁÉÍÓÚÃÕÂÊÎÔÛÇÀÈÌÒÙa-záéíóúãõâêîôûçàèìòù\w\s.()\/\-]+?)(?=\s+F[eé]rias\s+de\s|\s+Sal[aá]rio\s+Base|\s+\d{1,3}(?:\.\d{3})*,\d{2})/i,
  );
  const cargo = cargoMatch ? cargoMatch[1].trim() : null;

  // Extract codigoFolha (7-digit number before admission date)
  const folhaMatch = block.match(/(\d{7})\s+\d{2}\/\d{2}\/\d{4}Admiss/);
  const codigoFolha = folhaMatch ? folhaMatch[1] : null;

  // Extract referencia - value after name, format "220:00" or "13,80"
  const afterName = block.substring(
    (codeNameMatch.index ?? 0) + codeNameMatch[0].length - 1,
  );
  const refMatch = afterName.match(/^[\d,.:]+([\d]+[,:]\d+)/);
  let referencia: string | null = null;
  // Try a more direct approach: after name there should be a numeric value
  const refMatch2 = block.match(
    new RegExp(
      codigoFuncionario +
        '\\s+' +
        nomeCompleto.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') +
        '\\s+(\\d+[,:.]\\d+)',
    ),
  );
  if (refMatch2) {
    referencia = refMatch2[1];
  }

  // Extract rubricas (earnings and deductions)
  const rubricas = extractRubricas(block);

  // Calculate salarioBase from rubricas
  let salarioBase = 0;
  const salBaseRubrica = rubricas.find(
    (r) =>
      r.descricao.toLowerCase().includes('sal') &&
      r.descricao.toLowerCase().includes('base'),
  );
  if (salBaseRubrica) {
    salarioBase = salBaseRubrica.valor;
  }

  // Extract totals for this employee
  // After the separator "***... ____/____/______" there are 3 values: proventos, descontos, liquido
  const totaisMatch = block.match(
    /\*{15}\s+____\/____\/______\s+([\d]{1,3}(?:\.\d{3})*,\d{2})\s+([\d]{1,3}(?:\.\d{3})*,\d{2})\s+([\d]{1,3}(?:\.\d{3})*,\d{2})/,
  );

  let totalProventos = 0;
  let totalDescontos = 0;
  let salarioLiquido = 0;

  if (totaisMatch) {
    totalProventos = parseBRL(totaisMatch[1]);
    totalDescontos = parseBRL(totaisMatch[2]);
    salarioLiquido = parseBRL(totaisMatch[3]);
  } else {
    // Fallback: sum rubricas
    totalProventos = rubricas
      .filter((r) => r.tipo === 'PROVENTO')
      .reduce((sum, r) => sum + r.valor, 0);
    totalDescontos = rubricas
      .filter((r) => r.tipo === 'DESCONTO')
      .reduce((sum, r) => sum + r.valor, 0);
    salarioLiquido = totalProventos - totalDescontos;
  }

  // Extract Base INSS + aliquota
  const baseInssMatch = block.match(
    /Base\s+INSS:\s*([\d]{1,3}(?:\.\d{3})*,\d{2})\s*\(Aliq\.?:\s*([\d]{1,3}(?:\.\d{3})*,\d{1,4})%\)/,
  );
  const baseInss = baseInssMatch ? parseBRL(baseInssMatch[1]) : null;
  const aliquotaInss = baseInssMatch ? parseBRL(baseInssMatch[2]) : null;

  // Extract valor INSS from rubricas
  const inssRubrica = rubricas.find(
    (r) =>
      r.codigo === '903' || r.descricao.toLowerCase().includes('inss folha'),
  );
  const valorInss = inssRubrica ? inssRubrica.valor : null;

  // Extract Base FGTS + valor
  const baseFgtsMatch = block.match(
    /Base\s+FGTS:\s*([\d]{1,3}(?:\.\d{3})*,\d{2})\s*\(Valor:\s*([\d]{1,3}(?:\.\d{3})*,\d{2})\)/,
  );
  const baseFgts = baseFgtsMatch ? parseBRL(baseFgtsMatch[1]) : null;
  const valorFgts = baseFgtsMatch ? parseBRL(baseFgtsMatch[2]) : null;

  // Extract Base IRRF
  const baseIrrfMatch = block.match(
    /Base\s+IRRF\s+Folha:\s*([\d]{1,3}(?:\.\d{3})*,\d{2})/,
  );
  const baseIrrf = baseIrrfMatch ? parseBRL(baseIrrfMatch[1]) : null;
  const valorIrrf: number | null = null;

  return {
    codigoFuncionario,
    nomeCompleto,
    referencia,
    codigoFolha,
    dataAdmissao,
    dependentesIr,
    dependentesSf,
    cargo,
    salarioBase,
    totalProventos,
    totalDescontos,
    salarioLiquido,
    baseInss,
    aliquotaInss,
    valorInss,
    baseFgts,
    valorFgts,
    baseIrrf,
    valorIrrf,
    rubricas,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Rubrica extraction
// ─────────────────────────────────────────────────────────────────────────────

function extractRubricas(block: string): RubricaFolha[] {
  const rubricas: RubricaFolha[] = [];

  // Extract the portion before the separator (contains the rubricas)
  const sepIdx = block.indexOf('***************');
  const beforeSep = sepIdx !== -1 ? block.substring(0, sepIdx) : block;

  // Find the rubricas section: starts after "Função : {CARGO}" or "Férias..." with "Salário Base" or first rubrica
  const funcaoMatch = beforeSep.match(/Fun[cç][aã]o\s*:\s*/i);
  let rubricaSection = beforeSep;
  if (funcaoMatch && funcaoMatch.index !== undefined) {
    const afterFuncao = beforeSep.substring(
      funcaoMatch.index + funcaoMatch[0].length,
    );
    // Skip the cargo text and optional vacation info - find the first "Salário" which starts the rubricas
    const salarioIdx = afterFuncao.search(/Sal[aá]rio/i);
    if (salarioIdx !== -1) {
      rubricaSection = afterFuncao.substring(salarioIdx);
    } else {
      rubricaSection = afterFuncao;
    }
  }

  // The rubrica pattern in these PDFs is:
  // {Descrição} {valor BRL}{referência opcional NNN:NN}{código 3 dígitos}
  //
  // Examples:
  //   "Salário Base 1.966,00220:00001" → desc="Salário Base", val="1.966,00", ref="220:00", cod="001"
  //   "INSS Folha 218,36903" → desc="INSS Folha", val="218,36", cod="903"
  //   "Horas Extras 497,22026:00409" → desc="Horas Extras", val="497,22", ref="026:00", cod="409"
  //   "Empréstimo (Crédito Trabalhador) Parc. 11/12 64,32625" → desc="Empréstimo (Crédito Trabalhador) Parc. 11/12", val="64,32", cod="625"
  //   "Salário Base 295,00036:40001" → desc="Salário Base", val="295,00", ref="036:40", cod="001"
  //
  // Pattern breakdown:
  //   Description: starts with a letter, can contain letters, digits, spaces, dots, %, (), /
  //   Value: BRL format (digits with optional . thousands separator, comma decimal, 2 decimal digits)
  //   Optional reference: 3 digits + : + 2 digits (hours:minutes format)
  //   Code: exactly 3 digits at the end

  const rubricaRegex =
    /([A-Za-z\u00C0-\u024F][A-Za-z\u00C0-\u024F\d\s.%()\/\-,]*?)\s+([\d]{1,3}(?:\.\d{3})*,\d{2})(?:\d{3}:\d{2})?(\d{3})/g;

  let match: RegExpExecArray | null;
  while ((match = rubricaRegex.exec(rubricaSection)) !== null) {
    let descricao = match[1].trim();
    const valor = parseBRL(match[2]);
    const codigo = match[3];

    // Skip header/meta fields that might leak through
    if (
      descricao.includes('Base INSS') ||
      descricao.includes('Base FGTS') ||
      descricao.includes('Base IRRF')
    ) {
      continue;
    }

    // Clean up description: remove trailing "Parc." info numbers that leaked
    // e.g. "Empréstimo (Crédito Trabalhador) Parc. 11/12" should stay as-is
    descricao = descricao.replace(/\s+$/, '');

    rubricas.push({
      codigo,
      descricao,
      tipo: classificarRubrica(codigo),
      valor,
    });
  }

  return rubricas;
}

// ─────────────────────────────────────────────────────────────────────────────
// Footer/totals extraction
// ─────────────────────────────────────────────────────────────────────────────

function extractTotals(
  resumoText: string,
  fullText: string,
): {
  totalBruto: number;
  totalDescontos: number;
  totalLiquido: number;
  totalFuncionarios: number;
  totalInss: number;
  totalFgts: number;
  totalIrrf: number;
  totalSalarioFamilia: number;
} {
  // The footer values appear in this sequence after the labels:
  // "{totalBruto} Total Cotas Sal. Família {totalDescontos} {totalLiquido} {totalFuncionarios} {totalSalFamilia} {totalINSS} {totalFGTS} {totalIRRF}"
  const textToSearch = resumoText || fullText;

  const valoresMatch = textToSearch.match(
    /([\d]{1,3}(?:\.\d{3})*,\d{2})\s+Total\s+Cotas\s+Sal\.\s*Fam[ií]lia\s+([\d]{1,3}(?:\.\d{3})*,\d{2})\s+([\d]{1,3}(?:\.\d{3})*,\d{2})\s+(\d+)\s+(\d+)\s+([\d]{1,3}(?:\.\d{3})*,\d{2})\s+([\d]{1,3}(?:\.\d{3})*,\d{2})\s+([\d]{1,3}(?:\.\d{3})*,\d{2})/,
  );

  if (valoresMatch) {
    return {
      totalBruto: parseBRL(valoresMatch[1]),
      totalDescontos: parseBRL(valoresMatch[2]),
      totalLiquido: parseBRL(valoresMatch[3]),
      totalFuncionarios: parseInt(valoresMatch[4], 10),
      totalSalarioFamilia: parseInt(valoresMatch[5], 10),
      totalInss: parseBRL(valoresMatch[6]),
      totalFgts: parseBRL(valoresMatch[7]),
      totalIrrf: parseBRL(valoresMatch[8]),
    };
  }

  // Fallback: try individual extractions
  return {
    totalBruto:
      extractSingleValue(
        textToSearch,
        /Total\s+Geral.*?([\d]{1,3}(?:\.\d{3})*,\d{2})/,
      ) ?? 0,
    totalDescontos:
      extractSingleValue(
        textToSearch,
        /Total\s+de\s+Descontos.*?([\d]{1,3}(?:\.\d{3})*,\d{2})/,
      ) ?? 0,
    totalLiquido:
      extractSingleValue(
        textToSearch,
        /Total\s+L[ií]quido.*?([\d]{1,3}(?:\.\d{3})*,\d{2})/,
      ) ?? 0,
    totalFuncionarios:
      extractSingleInt(textToSearch, /Total\s+Funcion[aá]rios.*?(\d+)/) ?? 0,
    totalInss:
      extractSingleValue(
        textToSearch,
        /Total\s+INSS.*?([\d]{1,3}(?:\.\d{3})*,\d{2})/,
      ) ?? 0,
    totalFgts:
      extractSingleValue(
        textToSearch,
        /Total\s+FGTS.*?([\d]{1,3}(?:\.\d{3})*,\d{2})/,
      ) ?? 0,
    totalIrrf:
      extractSingleValue(
        textToSearch,
        /Total\s+IRRF.*?([\d]{1,3}(?:\.\d{3})*,\d{2})/,
      ) ?? 0,
    totalSalarioFamilia:
      extractSingleInt(
        textToSearch,
        /Total\s+Cotas\s+Sal\.\s*Fam[ií]lia.*?(\d+)/,
      ) ?? 0,
  };
}

function extractSingleValue(text: string, regex: RegExp): number | null {
  const match = text.match(regex);
  return match ? parseBRL(match[1]) : null;
}

function extractSingleInt(text: string, regex: RegExp): number | null {
  const match = text.match(regex);
  return match ? parseInt(match[1], 10) : null;
}
