/**
 * PDF text extraction and parsing for vacation documents (recibo e notificação de férias).
 * Handles PDFs generated by payroll systems like Senior, Dominio, Alterdata.
 */

export interface RubricaFerias {
  codigo: string;
  descricao: string;
  referencia: string | null;
  tipo: 'PROVENTO' | 'DESCONTO';
  valor: number;
}

export interface DadosFuncionarioFerias {
  codigoFuncionario: string;
  nomeCompleto: string;
  cargo: string | null;
  dataAdmissao: string | null;
  salarioBase: number;
  totalProventos: number;
  totalDescontos: number;
  salarioLiquido: number;
  baseInss: number | null;
  aliquotaInss: number | null;
  valorInss: number | null;
  baseFgts: number | null;
  valorFgts: number | null;
  baseIrrf: number | null;
  valorIrrf: number | null;
  rubricas: RubricaFerias[];
}

export interface DadosFerias {
  cnpj: string;
  razaoSocial: string;
  competencia: string;
  periodoInicio: string; // YYYY-MM-DD (Início do gozo)
  periodoFim: string; // YYYY-MM-DD (Fim do gozo)
  aquisitivoInicio: string | null; // DD/MM/YYYY
  aquisitivoFim: string | null; // DD/MM/YYYY
  gozoInicio: string; // DD/MM/YYYY
  gozoFim: string; // DD/MM/YYYY
  diasGozo: number;
  funcionario: DadosFuncionarioFerias;
  totalBruto: number;
  totalDescontos: number;
  totalLiquido: number;
  totalInss: number;
}

function parseBRL(str: string): number {
  if (!str) return 0;
  return parseFloat(str.replace(/\./g, '').replace(',', '.'));
}

function formatCnpj(digits: string): string {
  const d = digits.replace(/\D/g, '');
  if (d.length !== 14) return digits;
  return d.replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, '$1.$2.$3/$4-$5');
}

export function isReciboFerias(text: string): boolean {
  return (
    (text.includes('RECIBO DE FÉRIAS') ||
      text.includes('NOTIFICAÇÃO DE FÉRIAS') ||
      text.includes('F É R I A S')) &&
    !text.includes('FOLHA DE PAGAMENTO')
  );
}

export function extractDadosFerias(text: string): DadosFerias | null {
  if (!text.includes('RECIBO DE FÉRIAS') && !text.includes('NOTIFICAÇÃO DE FÉRIAS')) {
    return null;
  }

  // 1. CNPJ (14 dígitos)
  const cnpjMatch =
    text.match(/\b(\d{14})\b/) ||
    text.match(/\b(\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2})\b/);
  if (!cnpjMatch) return null;
  const cnpj = formatCnpj(cnpjMatch[1]);

  // 2. Nome do Colaborador
  // Aparece logo após o aviso de concessão de abono ou cabeçalho inicial
  const nameMatch =
    text.match(/Até 15 [^\n]+\n([A-ZÁÉÍÓÚÃÕÂÊÎÔÛÇÀÈÌÒÙ\s]+)\n/) ||
    text.match(/Funcionário:\s*\n([A-ZÁÉÍÓÚÃÕÂÊÎÔÛÇÀÈÌÒÙ\s]+)\n/);
  const nomeFuncionario = nameMatch ? nameMatch[1].trim() : '';
  if (!nomeFuncionario) return null;

  // 3. Período Aquisitivo
  const aquisitivoMatch = text.match(
    /(\d{2}\/\d{2}\/\d{4})\s+(\d{2}\/\d{2}\/\d{4})\s*\nPeríodo aquisitivo/,
  );
  const aquisitivoInicio = aquisitivoMatch ? aquisitivoMatch[1] : null;
  const aquisitivoFim = aquisitivoMatch ? aquisitivoMatch[2] : null;

  // 4. Período de Gozo
  const gozoMatch = text.match(
    /Período a ser gozado\s*\n(\d{2}\/\d{2}\/\d{4})\s+(\d{2}\/\d{2}\/\d{4})/,
  );
  if (!gozoMatch) return null;
  const gozoInicio = gozoMatch[1];
  const gozoFim = gozoMatch[2];

  // 5. Razão Social da Empresa
  const empresaMatch = text.match(
    /Período a ser gozado\s*\n\d{2}\/\d{2}\/\d{4}\s+\d{2}\/\d{2}\/\d{4}\s*\n(.*?)(?:\s+\d{5})?\n\s*\d{14}/,
  );
  let razaoSocial = empresaMatch ? empresaMatch[1].trim() : '';
  if (!razaoSocial) {
    const fallbackEmpresa = text.match(/Empresa:\s*([^\n]+)/);
    razaoSocial = fallbackEmpresa ? fallbackEmpresa[1].trim() : '';
  }

  // 6. Cargo / Função e Data de Admissão
  const cargoMatch = text.match(
    /\d{14}\s*\n(.*?)(?:Admissão:\s*(\d{2}\/\d{2}\/\d{4}))/,
  );
  const cargo = cargoMatch ? cargoMatch[1].trim() : null;
  const dataAdmissao = cargoMatch ? cargoMatch[2] : null;

  // 7. Código do Funcionário (6 dígitos após NOTIFICAÇÃO DE FÉRIAS)
  const codeMatch = text.match(/NOTIFICAÇÃO DE FÉRIAS\s*\n(\d{6})/);
  const codigoFuncionario = codeMatch ? codeMatch[1] : '';

  // 8. Dias de Duração
  const diasMatch = text.match(/NOTIFICAÇÃO DE FÉRIAS\s*\n\d{6}\s*\n(\d{1,2})/);
  const diasGozo = diasMatch ? parseInt(diasMatch[1], 10) : 30;

  // 9. Rubricas
  const rubricasSectionMatch = text.match(
    /férias abaixo:\s*\n([\s\S]*?)(?:\*{5,}|Líquido:)/,
  );
  const rubricas: RubricaFerias[] = [];
  if (rubricasSectionMatch) {
    const lines = rubricasSectionMatch[1].split('\n');
    for (const line of lines) {
      const rMatch = line.trim().match(/^(\d{3})\s+(.+?)\s+([\d.,]+)$/);
      if (rMatch) {
        const codigo = rMatch[1];
        const descricao = rMatch[2].trim();
        const valor = parseBRL(rMatch[3]);
        const num = parseInt(codigo, 10);
        const tipo: 'PROVENTO' | 'DESCONTO' =
          num >= 900 || (num >= 600 && num < 700) ? 'DESCONTO' : 'PROVENTO';
        rubricas.push({ codigo, descricao, referencia: null, tipo, valor });
      }
    }
  }

  // 10. Totais calculados das rubricas
  const totalBruto = rubricas
    .filter((r) => r.tipo === 'PROVENTO')
    .reduce((acc, r) => acc + r.valor, 0);
  const totalDescontos = rubricas
    .filter((r) => r.tipo === 'DESCONTO')
    .reduce((acc, r) => acc + r.valor, 0);
  const totalLiquido =
    Math.round((totalBruto - totalDescontos) * 100) / 100;

  const inssRubrica = rubricas.find(
    (r) => r.codigo === '902' || r.descricao.toUpperCase().includes('INSS'),
  );
  const totalInss = inssRubrica ? inssRubrica.valor : 0;

  // Formatação de datas ISO
  const [dInicio, mInicio, yInicio] = gozoInicio.split('/');
  const periodoInicio = `${yInicio}-${mInicio}-${dInicio}`;
  const competencia = `${mInicio}/${yInicio}`;

  const [dFim, mFim, yFim] = gozoFim.split('/');
  const periodoFim = `${yFim}-${mFim}-${dFim}`;

  return {
    cnpj,
    razaoSocial,
    competencia,
    periodoInicio,
    periodoFim,
    aquisitivoInicio,
    aquisitivoFim,
    gozoInicio,
    gozoFim,
    diasGozo,
    funcionario: {
      codigoFuncionario,
      nomeCompleto: nomeFuncionario,
      cargo,
      dataAdmissao,
      salarioBase: totalBruto,
      totalProventos: totalBruto,
      totalDescontos,
      salarioLiquido: totalLiquido,
      baseInss: totalBruto,
      aliquotaInss: null,
      valorInss: totalInss,
      baseFgts: null,
      valorFgts: null,
      baseIrrf: null,
      valorIrrf: null,
      rubricas,
    },
    totalBruto,
    totalDescontos,
    totalLiquido,
    totalInss,
  };
}
